name: Docker Publish

on:
  create:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string
      mlflow_version:
        description: 'MLflow version (defaults to tag)'
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
            echo "mlflow_version=${{ inputs.mlflow_version || inputs.tag }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "mlflow_version=$TAG" >> $GITHUB_OUTPUT
          else
            echo "Not a tag. Skipping."
            exit 78
          fi

      - name: Validate tag format
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"
          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag '$TAG' must follow semantic versioning (e.g., 3.1.4)"
            exit 1
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: random1st/mlflow-jfrog:${{ steps.get_tag.outputs.tag }}
          build-args: |
            MLFLOW_VERSION=${{ steps.get_tag.outputs.mlflow_version }}
          
